### ISSUE TITLE
link / mirror the TFTP root content also to the HTTP / NGINX root

### ISSUE THREAD

**Issue by bofhbug** [netbootxyz/webapp#2]
please link / mirror the TFTP root content, also to the HTTP / NGINX root dir
so all the files can also Accessed via http and / or the webapp can fully usesd with http/https only

**Comment by thelamer** [comment]
You can do this yourself using a symlink if you choose to :  (from assets directory host or container level)
```
ln -s /config/menus ipxe
```
As this application is designed from the ground up to be run in a local setup this symlink should suffice no ? 
Keep in mind the core boot rom will never load your local HTTP/S server unless you custom compile it. I would highly recommend you review the code embedded in the boot rom: 
https://github.com/netbootxyz/netboot.xyz/blob/development/roles/netbootxyz/templates/disks/netboot.xyz.j2
There is logic to detect pulling from a local TFTP server and to pull from that instead of the public boot.netboot.xyz endpoint. But local HTTP server detection would not be possible.

I think this might be what you are looking for the projects document on actually self hosting a netboot.xyz clone: 
https://netboot.xyz/selfhosting/
