### ISSUE TITLE
[Feature Request] Download netboot installer ISOs

### ISSUE THREAD

**Issue by kaysond** [netbootxyz/webapp#5]
I'm using netboot to install Ubuntu 20.04. While I can use the webapp to grab a local copy of the netboot image, that itself goes and downloads the full ubuntu installer which takes far longer. It would be nice for the webapp to include an option to download that as well.

In the Ubuntu case, that iso is being set here, so it seems like it could be programmatically expanded and added to the list of assets...
```
:sub_boot
imgfree
isset ${dhcp-server} && set netboot_params ip=dhcp url=http://releases.ubuntu.com/${codename}/ubuntu-${version_number}-live-server-${arch_a}.iso || set netboot_params
echo Loading Ubuntu Subiquity Network Installer...
kernel ${kernel_url}vmlinuz root=/dev/ram0 ramdisk_size=1500000 ${netboot_params} ${install_params} initrd=initrd ${cmdline}
initrd ${kernel_url}initrd
echo
echo MD5sums:
md5sum vmlinuz initrd
boot
```

**Comment by thelamer** [comment]
This webapp is simply an extension of the parent project and a helper to allow users to download assets we specifically host and easily modify their menu files on a local network. 

At the core of your issue is the inclusion of Ubuntu live server CD being a bootable option, normally we would only host assets on github if they needed some kind of special modification to be functional. I do not see this application beginning to support pulling in web bootable images or disks from external sources we do not control. Though with this application you can make you custom boot entry and place your assets in the baked in webserver to serve from your local network. 

I hope that makes sense.
